var nome = "Matheus";
var idade = 16;
var city = "Jau";
console.log("Olá,", nome, "voce tem", idade, "de idade, e mora na cidade de", city, "Seja bem vindo!");
let x = 50;
let y = 60;
let adi = x + y;
let sub = x - y;
let mult = x * y;
let div = x / y;
console.log("A Adição de x + y" adi);